Compete in TCO2021 Europe Qualifier, Div 1
successful challenges: 1/1 ^_^
- new coder <- good hunch
problems: 1 AC / 1 submissions (2 opened)
failed systests: 0 :-)
- 5 coders failed 250-pt in the room :-O

rank in the room: 7/11 (12 competing)
-> highest rated green coder in the room
   - blue coder below me! (thanks to challenge points)
   - yellow coder below me (2 failed systest, 0 challeng points)
- would have been 5/11 w/ Kanten-4205's challenge
  - by >50 pts! :-/
    - but hard to construct challenging input

rank in the division: 140/420 (~? present)
- mostly higher-rated (historically blue) coders above me!
  - ~20-30 blue coder below me!
  - ~15-20 yellow coders below me!!
  - 2 red coders below me!!!
PERCENTILE: >66% :-/ (>?%)
- but Div 1
  - against yellow, reds and targets!
rating: 1133 +68 :-O :-O -> 1201 :-) :-) :-) ^_^ ^_^ [blue] => (new highest) -> in spite of painful troubles in 250-pts? Wow! :-O
- just so-so blue, but still!
  -> historical moment!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  => SH*T, I JUST BECAME BLUE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
     - I guess competing in Div 1 now
       - must practice Div 2 Hard to stay on track!
         - minimum Div 2 Medium
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Analysis
--------

- well-rested, well-slept
- stressful, annoying rounds
  -> painful 250-pt
     - implementation
     - mismatching compilers w/ TC :-/
- too many presubmit bugs in 250-pt :-/
  - painful

250-pt:
- AC!! yes!
- felt like Div 1 Easy
  - tricky to implement

- presubmit bugs:
  - "RIP c++ users who got compilation errors because of the method signature used the same function name Sort.. I wasted at least 50 points there trying to debug"
    - me too :-(
    - both YCM and g++ complained
    => CHECK FOR CLASH OF NAMES!!
    => WHEN UNSURE ABOUT COMPILATION ERROR, TRY PREPENDING "STD::"!
  - segfault
    - forgotten size intialization
      - i.e. `vector<pair<string,int>> scores;`
        - instead of `vector<pair<string,int>> scores(N);`
      - tricky hidden segfault :-/
    => COMPILE CONTINUALLY/AFTER EVERY LOGICAL BLOCK OF CODE!!!!!
    => BINARY SEARCH VIA MSG("HERE") TO FIND THE CAUSE OF SEGFAULT!!
  - problems w/ debug-printing
    - can't print `vector<pair<string,int>>`
      - clash of <<= and << operators
    => DON'T WASTE TIME FIGURING OUT WHAT CAN BE DEBUG PRINTED OR NOT
  - hesitation w/ `ranking[i]=scores[i].S;`
    - reverse mapping `ranking[scores[i].S]=i;`?
      -> no!
    => THINK CAREFULLY HOW TO STORE RESULTING RANKING!
  - typo: swapped .F and .S for string counting :-/
    => ALWAYS STORE PAIRS AS (INDEX, PAYLOAD)!!
       - MORE NATURAL & KEEP IT SAME ALWAYS!
  - out-of-bound error: `i >= 0` instead of `i-25 >= 0`
    - no compilation error/exception :-(
    => THINK CAREFULLY & AHEAD HOW YOU USE INDICES IN FOR LOOP!!!
       => ONLY THEN TYPE THE CONDITION!!
    => OR LEAVE IT BLANK UNTIL THE BODY IS IMPLEMENTED/CLEAR!
  - misunderstood `cmp` return type
    - should have been int for {-1,0,1}, but returned {true, false}
      - guard against SGN(...)==0
        - then return SGN(...)==1
      - i.e. `int cmp=SGN(count(a.F.begin()+i-25,a.F.begin()+i,'1')
                        - count(b.F.begin()+i-25,b.F.begin()+i,'1'));`
        - instead of `bool cmp=count(a.F.begin()+i-25,a.F.begin()+i,'1')
                             > count(b.F.begin()+i-25,b.F.begin()+i,'1');`
      => REMEBER THAT OPERATOR< RETURNS ONLY {0,1} FOR INTS!!
         => OPERATOR< RETURNS ONLY {-1,0,1} ONLY FOR STRINGS!
  - hesitation w/ reverse sorting the scores
    - re-design
      - sort decreasingly, instead of after-sort reverse
    => PLAN AHEAD CAREFULLY HOW TO SORT!!
       - INCREASING OR DECREASING?
=> coding kata!

600-pt:
- unsolved :-/
- BFS/DFS traversal
  - set to pow(2) or pow(2)-1?
- problems with debug printing unordered_map<> :-/
  - Vimcoder operator<< overload sucks! :-(
=> to upsolve!

- succesfully challenged new coder D3structor's solution
  - suspiciously short
  - used the most tricky solution (i.e. sample 2)
    - one of 2 first challenges in the room
=> always focus on new coders, esp. if they more pts from the solution
than higher rated coders
=> PREPARE CHALLENGE INPUT
   => ESPECIALLY (OR AT LEAST) PICK THE MOST "CHALLENGING" SAMPLE INPUT!

- should have challenged new coder D3structor's 600-pts
  - challenged
  - faster: directly there
    - compare the code w/ higher rated coders' solutions
    - and guess when too short :-/
      - but difficult to construct!

- worked on challenging green coder Kanten-4205's solution
  - failed systests!
  - suspicious handling of "ending" (see the attached screenshot)
    <- accumulates only the last shot of each round?
       -> possible challenge, but tricky to construct and not enough time
=> TRY HARDER TO READ OTHER'S SOLUTION

Signed-off-by: Karel Ha <mathemage@gmail.com>