Codeforces 261B, Div 2
WA #5 :-/
AC !!! [in 7+3=10m]

Analysis:
- pre-submit hesitations:
  <- search C++ reference for `map::{front,back}`
     - used `map::{r}begin` instead
  - compilation error:
    <- forgotten `->{F,S}` for the map key-value pair
    <- used `*map.{F,S}`
       - instead of `*map->{F,S}`
  - swapped order `counter.begin()->F - counter.rbegin()->F;`
    - instead of `counter.rbegin()->F - counter.begin()->F;`

- WA #5:
  <- testcase when min bi==max bi (see `in4`)
     - handle via number of combinations (i.e. pairs)
=> ALWAYS CONSIDER EDGE CASES!!
   - E.G. WHEN MIN == MAX IN A GIVEN SEQUENCE!

Signed-off-by: Karel Ha <mathemage@gmail.com>